### ISSUE TITLE
Are you sure this is current?

### ISSUE THREAD

**Issue by barnaba** [luaduck/suds#1]
Hey,

I tried looking through the code. Seems like it's not what you use on your servers? Couldn't find any code referring to the "!reset" command, which works with S1 and S3 bots…

**Comment by duckfullstop** [comment]
Aw snap, you're right. I did make some changes to the codebase directly on the server, but as this is a direct fork those obviously aren't in there. I'll commit !reset and the other couple changes tonight.

**Comment by barnaba** [comment]
Thanks.
