### ISSUE TITLE
Does not run

### ISSUE THREAD

**Issue by InTheMorning** [luaduck/suds#6]
I've cloned the libottdadmin2 folder to within the suds folder.

When I try to run __init.py__ i get:
`Traceback (most recent call last):
  File "__init__.py", line 39, in <module>
    import enums
  File "/home/citizen/openttd/supybot/plugins/suds/enums.py", line 17, in <module>
    from libottdadmin2.enums import EnumHelper
ImportError: cannot import name 'EnumHelper' from 'libottdadmin2.enums' (/home/citizen/openttd/supybot/plugins/suds/libottdadmin2/enums.py)
INFO 2020-05-16T19:02:13 Shutdown initiated.
INFO 2020-05-16T19:02:13 Killing Driver objects.
INFO 2020-05-16T19:02:13 Killing Irc objects.
INFO 2020-05-16T19:02:13 Shutdown complete.
`

It seems Xaroth has refactored his enums.py.

**Comment by duckfullstop** [comment]
Yeah, Xaroth majorly refactored the library in the move to Python 3. In the interim, please use [our fork](https://github.com/ropenttd/libottdadmin2) with Python 2.

While it would be nice to refactor this to the new library and Python 3, Suds is kind of EOL from my perspective - I'm working on its replacement as we speak, but it's a month or two off being ready for use.

Let me know if this compromise gets you going!
